# Admin-facing routes

planedo_login:
  path: /login
  controller: Crell\Bundle\Planedo\Controller\LoginController::index

planedo_logout:
  path: /logout
  controller: Crell\Bundle\Planedo\Controller\LoginController::logout

planedo_forgot_password_request:
  path: /reset-password
  controller: Crell\Bundle\Planedo\Controller\ResetPasswordController::request

planedo_check_email:
  path: /check-email
  controller: Crell\Bundle\Planedo\Controller\ResetPasswordController::checkEmail

planedo_reset_password:
  path: /reset/{token}
  controller: Crell\Bundle\Planedo\Controller\ResetPasswordController::reset

planedo_admin:
  path: /admin
  controller: Crell\Bundle\Planedo\Controller\Admin\DashboardController::index

planedo_user_settings:
  path: /admin/user-settings
  controller: Crell\Bundle\Planedo\Controller\UserSettingsController::index
