# Public facing routes

planedo_blog_roll:
  path: /blogroll
  controller: Crell\Bundle\Planedo\Controller\BlogRollController::index

planedo_atom_main:
  path: /atom
  controller: Crell\Bundle\Planedo\Controller\FeedController::atomFeed

planedo_rss_main:
  path: /rss
  controller: Crell\Bundle\Planedo\Controller\FeedController::rssFeed

planedo_html_main:
  path: /
  controller: Crell\Bundle\Planedo\Controller\HtmlFeedController::index
