# Admin-facing routes

crell_planedo_login:
  path: /login
  controller: Crell\Bundle\Planedo\Controller\LoginController::index

crell_planedo_logout:
  path: /logout
  controller: Crell\Bundle\Planedo\Controller\LoginController::logout


crell_planedo_admin:
  path: /admin
  controller: Crell\Bundle\Planedo\Controller\Admin\DashboardController::index

crell_planedo_user_settings:
  path: /admin/user-settings
  controller: Crell\Bundle\Planedo\Controller\UserSettingsController::index
