---
name: Quality Assurance
on:
  push: ~
  pull_request: ~

jobs:
  build-php:
    name: PHP ${{ matrix.php }} / Symfony ${{ matrix.symfony }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1']
        symfony: ['^5.4', '^6.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: composer:v2

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ matrix.php }}-composer-${{ matrix.symfony }}

      - name: Install
        run: |
          sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'${{ matrix.symfony }}'"/' composer.json;
          composer update --prefer-dist --no-progress
          composer info
          git checkout composer.json

      - name: Lint
        run: composer test:php:lint

      - name: CGL
        run: composer test:php:cgl

      - name: Unit Tests
        run: composer test:php:unit
